// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEvFOKTs-0oFh1G-pRUWlvFmGn2L4_450',
    appId: '1:960749792164:android:969bc9a0a30570d1d8af31',
    messagingSenderId: '960749792164',
    projectId: 'jkautomed',
    storageBucket: 'jkautomed.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0r-4DcHynqkPUk_hkZW0Z7Xk0a1mVxfM',
    appId: '1:960749792164:web:fe6c1889d3a1818dd8af31',
    messagingSenderId: '960749792164',
    projectId: 'jkautomed',
    authDomain: 'jkautomed.firebaseapp.com',
    storageBucket: 'jkautomed.firebasestorage.app',
    measurementId: 'G-7JC208Z5M6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8pq2FucWC9TogIQzXuw6-1KgRT5KodLA',
    appId: '1:960749792164:ios:aa5243a3fa8720d2d8af31',
    messagingSenderId: '960749792164',
    projectId: 'jkautomed',
    storageBucket: 'jkautomed.firebasestorage.app',
    iosBundleId: 'com.dbvertex.jkautoparts.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0r-4DcHynqkPUk_hkZW0Z7Xk0a1mVxfM',
    appId: '1:960749792164:web:7da5a72dac9942fad8af31',
    messagingSenderId: '960749792164',
    projectId: 'jkautomed',
    authDomain: 'jkautomed.firebaseapp.com',
    storageBucket: 'jkautomed.firebasestorage.app',
    measurementId: 'G-X2GWRZ1T17',
  );

}